FROM node:alpine
USER root
## && apt-get install nginx -y
COPY main.js /bin/main.js
COPY execute.js /bin/execute.js
COPY package.json /bin/package.json
RUN apk search npm
RUN apk add --update nodejs npm
RUN cd /bin && npm i
RUN node -v
CMD ["node", "/bin/main.js"]
EXPOSE 80
